export const GET_NOTIFICATIONS = 'timeline/GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_COMPLETED =
	'timeline/GET_NOTIFICATIONS_COMPLETED';
export const GET_NOTIFICATIONS_FAILED = 'timeline/GET_NOTIFICATIONS_FAILED';

export const GET_NOTIFICATION_BY_ID = 'timeline/GET_NOTIFICATION_BY_ID';
export const GET_NOTIFICATION_BY_ID_COMPLETED =
	'timeline/GET_NOTIFICATION_BY_ID_COMPLETED';
export const GET_NOTIFICATION_BY_ID_FAILED =
	'timeline/GET_NOTIFICATION_BY_ID_FAILED';

export const ADD_NOTIFICATION_ENTRY = 'timeline/ADD_NOTIFICATION_ENTRY';
export const ADD_NOTIFICATION_ENTRY_COMPLETED =
	'timeline/ADD_NOTIFICATION_ENTRY_COMPLETED';
export const ADD_NOTIFICATION_ENTRY_FAILED =
	'timeline/ADD_NOTIFICATION_ENTRY_FAILED';
